[package]
name = "ci_build"
version = "0.0.3"
authors = ["Thom Pennington <Thom@litmushealth.com>"]

[dependencies]
iron = "*"
plugin = "*" # for iron
typemap = "0.3.3"
router = "*"
slog = "*"
slog-term = "*"
slog-async = "*"
lazy_static = "0.2"
urlencoded = "*"
itertools = "*"
clippy = {version = "*", optional = true}

[features]
default = []
