# Chain Indent Config
#
# Block:
# let lorem = ipsum
#     .dolor()
#     .sit()
#     .amet()
#     .consectetur()
#     .adipiscing()
#     .elit();
#
# Visual:
# let lorem = ipsum.dolor()
#                  .sit()
#                  .amet()
#                  .consectetur()
#                  .adipiscing()
#                  .elit();
#
chain_indent = "Visual"

# Closure Block Indent Threshold Config
#
# Closures shorter than closure_block_indent_threshold:
# lorem_ipsum(|| {
#                 println!("lorem");
#                 println!("ipsum");
#                 println!("dolor");
#                 println!("sit");
#                 println!("amet");
#             });
#
# Closures longer than closure_block_indent_threshold:
# lorem_ipsum(|| {
#     println!("lorem");
#     println!("ipsum");
#     println!("dolor");
#     println!("sit");
#     println!("amet");
#     println!("consectetur");
#     println!("adipiscing");
#     println!("elit");
# });
#
# closure_block_indent_threshold = -1 means never do the "longer than" option
#
closure_block_indent_threshold = -1

# Match Block Trailing Comma Config
#
# false:
# match lorem {
#     Lorem::Ipsum => {
#         println!("ipsum");
#     }
#     Lorem::Dolor => println!("dolor"),
# }
#
# true:
# match lorem {
#     Lorem::Ipsum => {
#         println!("ipsum");
#     },
#     Lorem::Dolor => println!("dolor"),
# }
#
match_block_trailing_comma = true

# Reorder Imported Names Config
#
# false:
# use super::{lorem, ipsum, dolor, sit};
#
# true:
# use super::{dolor, ipsum, lorem, sit};
#
reorder_imported_names = true

# Reorder Imports Config
#
# false:
# use lorem;
# use ipsum;
# use dolor;
# use sit;
#
# true:
# use dolor;
# use ipsum;
# use lorem;
# use sit;
#
reorder_imports = true

# Reorder Imports in Group Config
# false:
# use std::mem;
# use std::io;
#
# use lorem;
# use ipsum;
# use dolor;
# use sit;
#
# true:
# use std::io;
# use std::mem;
# 
# use dolor;
# use ipsum;
# use lorem;
# use sit;
#
# NOTE: Only applies if reorder_imports = true
reorder_imports_in_group = true

# Format Strings Config
#
# false:
# let lorem = "ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit";
#
# true:
# let lorem =
#     "ipsum dolor sit amet consectetur \
#      adipiscing elit lorem ipsum dolor sit";
#
# NOTE FROM ROB: rustfmt does horrible things to multiline string literals
#                pretty much no matter what we set here. Be careful.
format_strings = true
